Repository samtuap/dongsanginong-client, pull requests merged in 2024-11, with the labels that each got.

#264 chore: 디자인 수정
  src/views/product/farm/FarmPackageDetail.vue
  src/views/product/review/ReviewCreate.vue
  src/views/product/seller/ProductList.vue
  src/views/product/seller/SellerDiscountCreate.vue
  src/views/product/seller/SellerDiscountManagement.vue
Labels: 🧹 chore

#266 chore: 판매자 결제 페이지 진입 금지
  src/views/product/farm/FarmPackageDetail.vue
Labels: 🧹 chore

#269 fix: 스크롤 위치 수정
  src/router/index.js
Labels: 🚧 fix

#271 chore: 상품 등록 시 에디터 추가 및 농장 생성 후 id 저장
  src/views/product/farm/FarmCreate.vue
  src/views/product/farm/FarmPackageDetail.vue
  src/views/product/package/ProductCreate.vue
Labels: 🧹 chore, 🚧 fix

#272 공지 생성 오류 수정 및 리뷰 이미지 오류 수정
  src/views/product/farm/FarmPackageDetail.vue
  src/views/product/farmNotice/FarmNoticeCreate.vue
  src/views/product/farmNotice/FarmNoticeUpdate.vue
  src/views/product/review/ReviewUpdate.vue
Labels: 🧹 chore

#276 fix: 농장 목록 > 카테고리도 검색 되도록 기능 수정
  src/views/product/farm/farmListSample.vue
Labels: 🚧 fix

#275 chore: 상품 수정 화면에 에디터 추가 및 상품 상세 정보에서 수정 기능 제거
  src/views/product/farm/FarmPackageDetail.vue
  src/views/product/seller/ProductUpdate.vue
Labels: 🧹 chore

#278 fix: 유효기간이 지난 쿠폰 목록 미포함 수정
  src/views/live/chat/ChatBox.vue
Labels: 🚧 fix
