Repository samtuap/dongsanginong-client, pull requests merged in 2024-09, with the labels that each got.

#2 setting: vuetify color 세팅, Pr/Issue 템플릿 세팅
  .github/ISSUE_TEMPLATE/feature.md
  .github/pull_request_template.md
  package-lock.json
  package.json
  src/components/HelloWorld.vue
  src/plugins/vuetify.js
  src/store/index.js
Labels: ⚙️setting

#5 setting: 인터셉터 세팅
  .gitignore
  package-lock.json
  src/components/HelloWorld.vue
  src/main.js
  src/views/AboutView.vue
  src/views/HomeView.vue
Labels: ⚙️setting

#8 feat: header 생성
  public/index.html
  public/inongLogo.png
  public/notifications.png
  public/searchLogo.png
  src/views/AboutView.vue
  src/views/MainHeader.vue
Labels: enhancement

#12 feature: 농장 > 공지사항(커뮤니티) 목록 화면 구현
  public/comment.png
  src/components/header/MainHeader.vue
  src/router/FarmNoticeRouter.js
  src/router/index.js
  src/views/AboutView.vue
  src/views/product/farmNotice/FarmNoticeList.vue
Labels: 🥦 feature

#15 feat: 사장님 페이지 사이드바, 매출 내역 페이지(미완)
  package.json
  src/components/sidebar/SellerSidebar.vue
  src/router/index.js
  src/router/sellerRouter.js
  src/views/AboutView.vue
  src/views/product/seller/SellerSalesDetail.vue
  src/views/seller/SellerSalesDetail.vue
Labels: 🥦 feature

#19 feat: 공지 디테일 화면 & 댓글 화면 구현
  public/plus.png
  src/router/farmNoticeRouter.js
  src/router/index.js
  src/views/product/farmNotice/FarmNoticeList.vue
  src/views/product/farmNotice/NoticeDetailWithComment.vue
Labels: 🥦 feature

#21 feat: 로그인 버튼 클릭 시 나타나는 로그인 페이지
  src/assets/google_login.png
  src/assets/kakao_login.png
  src/components/header/MainHeader.vue
  src/main.js
  src/router/index.js
  src/views/member/login/GoogleCallback.vue
  src/views/member/login/KakaoCallback.vue
  src/views/member/login/MemberLoginPage.vue
Labels: 🥦 feature

#26 feat: 일반 회원 회원가입 페이지
  src/router/index.js
  src/views/member/login/GoogleCallback.vue
  src/views/member/login/KakaoCallback.vue
  src/views/member/login/MemberSignIn.vue
  src/views/member/login/MemberSignUp.vue
Labels: 🥦 feature

#25 feat: 판매자 회원가입 페이지
  src/router/sellerRouter.js
  src/views/product/seller/SellerSignUp.vue
Labels: 🥦 feature

#28 feat: 사장님 페이지 > 주문 및 배송 관리 화면 구현 & chore: 사장님 페이지 사이드바 수정
  src/components/sidebar/SellerSidebar.vue
  src/router/sellerRouter.js
  src/views/order/delivery/DeliveryManageList.vue
Labels: 🥦 feature

#31 chore: member router 및 경로 수정
  src/components/header/MainHeader.vue
  src/router/index.js
  src/router/memberRouter.js
  src/views/member/login/GoogleCallback.vue
  src/views/member/login/KakaoCallback.vue
Labels: 🧹 chore

#32 feat:
  src/router/farmNoticeRouter.js
  src/views/product/seller/SellerSalesDetail.vue
Labels: 🥦 feature
