Repository samtuap/dongsanginong-client, pull requests merged in 2024-10, with the labels that each got.

#36 feat: 일반 회원 로그인 시 localStorage > memberId 저장
  src/views/member/login/GoogleCallback.vue
  src/views/member/login/KakaoCallback.vue
  src/views/member/login/MemberSignUp.vue
Labels: 🥦 feature

#40 feat:쿠폰 생성
  src/router/couponRouter.js
  src/router/index.js
  src/router/sellerRouter.js
  src/views/order/coupon/CouponCreate.vue
  src/views/order/coupon/CouponCreateList.vue
  src/views/product/farmNotice/FarmNoticeCreate.vue
Labels: 🥦 feature

#39 feat:판매자 탈퇴 기능
  src/components/header/MainHeader.vue
  src/router/sellerRouter.js
  src/views/member/login/MemberSignIn.vue
  src/views/product/seller/SellerSignIn.vue
  src/views/product/seller/SellerSignUp.vue
  src/views/product/seller/SellerWithDraw.vue
Labels: 🥦 feature, 🚧 fix

#43 feat: 댓글 작성 / 수정 / 삭제 기능 구현
  src/views/product/farmNotice/FarmNoticeList.vue
  src/views/product/farmNotice/NoticeDetailWithComment.vue
Labels: 🥦 feature, 🧹 chore

#44 feat: 일반 회원 마이 페이지 구현
  package.json
  public/favicon.ico
  src/components/header/MainHeader.vue
  src/components/sidebar/MemberSidebar.vue
  src/main.js
  src/router/memberRouter.js
  src/views/member/login/GoogleCallback.vue
  src/views/member/login/KakaoCallback.vue
  src/views/member/login/MemberSignUp.vue
  src/views/member/myPage/MemberMyPage.vue
Labels: 🥦 feature

#46 feat: 농장 리스트 페이지 구현
  src/router/farmRouter.js
  src/router/index.js
  src/views/order/delivery/DeliveryManageList.vue
  src/views/product/farm/FarmList.vue
Labels: 🥦 feature

#48 chore: 로그인 로직 관련 Modal 크기 수정
  src/components/header/MainHeader.vue
  src/views/member/login/GoogleCallback.vue
  src/views/member/login/KakaoCallback.vue
  src/views/member/login/MemberSignUp.vue
  src/views/member/myPage/MemberMyPage.vue
Labels: 🧹 chore

#51 feat: 일반 회원 전화번호 수정
  src/components/sidebar/MemberSidebar.vue
  src/router/memberRouter.js
  src/views/member/myPage/MemberMyPage.vue
  src/views/member/myPage/MemberPhoneUpdate.vue
Labels: 🥦 feature

#53 feat: 판매자 농장 생성
  public/baseBannerImage.png
  public/fileUpload.png
  public/plusButton.png
  src/router/farmRouter.js
  src/views/product/farm/FarmCreate.vue
  src/views/product/seller/SellerWithDraw.vue
Labels: 🥦 feature

#55 feat: 일반 회원 주소지 수정
  src/components/sidebar/MemberSidebar.vue
  src/router/memberRouter.js
  src/views/member/myPage/MemberAddressUpdate.vue
Labels: 🥦 feature

#56 feat: 처음 농장 생성 시 모달 추가
  src/components/header/MainHeader.vue
  src/views/product/farm/FarmCreate.vue
Labels: 🥦 feature

#59 feat: 쿠폰 리스트 구현, 쿠폰 생성 변경
  src/router/sellerRouter.js
  src/views/order/coupon/CouponCreate.vue
  src/views/order/coupon/CouponList.vue
Labels: 🥦 feature

#61 feat: 라이브 목록 조회 & 즐겨찾기 한 라이브 목록 조회
  src/components/header/MainHeader.vue
  src/components/sidebar/SellerSidebar.vue
  src/router/index.js
  src/router/liveRouter.js
  src/views/live/live/LiveList.vue
Labels: 🥦 feature

#63 feat: 일반 회원 농장 즐겨찾기 및 구독 정보 조회
  src/components/sidebar/MemberSidebar.vue
  src/router/memberRouter.js
  src/views/member/myPage/MemberFavorite.vue
Labels: 🥦 feature

#62 feat: 판매자 상품 등록
  src/router/sellerRouter.js
  src/views/product/package/ProductCreate.vue
Labels: 🥦 feature

#69 fix: farm list 정렬
  src/views/product/farm/FarmList.vue
Labels: 🚧 fix

#70 feat: 판매자 상품 관리 화면 구현
  src/components/header/MainHeader.vue
  src/components/sidebar/SellerSidebar.vue
  src/router/sellerRouter.js
  src/views/product/farm/FarmCreate.vue
  src/views/product/package/ProductCreate.vue
  src/views/product/seller/ProductList.vue
  src/views/product/seller/ProductUpdate.vue
  src/views/product/seller/SellerSignIn.vue
  src/views/product/seller/SellerSignUp.vue
  src/views/product/seller/SellerWithDraw.vue
Labels: 🥦 feature, 🚧 fix

#72 feat: 농장 디테일 배너사진 + 메뉴바 컴포넌트
  src/components/menubar/FarmMenuComponent.vue
  src/router/farmNoticeRouter.js
  src/router/farmRouter.js
  src/views/product/farm/FarmDetailDescription.vue
  src/views/product/farm/FarmList.vue
  src/views/product/farmNotice/FarmNoticeList.vue
  src/views/product/farmNotice/NoticeDetailWithComment.vue
Labels: 🥦 feature

#75 feat: 구매자 쿠폰 리스트 구현
  public/coupon2.png
  public/coupon3.png
  src/components/sidebar/MemberSidebar.vue
  src/router/memberRouter.js
  src/views/order/coupon/MemberCouponList.vue
Labels: 🥦 feature

#77 feat: 일반 회원 결제 내역 조회
  package.json
  src/components/sidebar/MemberSidebar.vue
  src/router/index.js
  src/router/memberRouter.js
  src/router/receiptRouter.js
  src/views/member/myPage/MemberPaymentList.vue
  src/views/member/myPage/MemberPhoneUpdate.vue
  src/views/order/receipt/MemberPaymentReceipt.vue
Labels: 🥦 feature

#73 chore: 판매자 상품 관리 화면 수정
  src/views/product/package/ProductCreate.vue
  src/views/product/seller/ProductList.vue
  src/views/product/seller/ProductUpdate.vue
Labels: 🧹 chore

#80 feat: 판매 중인 패키지 설명과 패키지 목록 조회
  src/router/farmRouter.js
  src/views/product/farm/FarmPackageList.vue
Labels: 🥦 feature

#81 feat: 라이브 스트리밍 구현
  package.json
  public/live.png
  src/components/video/OvVideo.vue
  src/components/video/UserVideo.vue
  src/router/liveRouter.js
  src/views/live/live/LiveList.vue
Labels: 🥦 feature

#87 feat: 헤더에 fcm 알림 수신 기능 추가
  .gitignore
  package.json
  public/firebase-messaging-sw.js
  src/components/HelloWorld.vue
  src/components/header/MainHeader.vue
  src/store/fcmNoti.js
  src/store/index.js
Labels: 🥦 feature

#89 chore: 라이브 목록 및 세션 관련 이슈 해결
  src/components/menubar/FarmMenuComponent.vue
  src/router/liveRouter.js
  src/views/live/live/LiveList.vue
  src/views/live/live/LiveSession.vue
  src/views/product/farm/FarmPackageList.vue
Labels: 🥦 feature, 🧹 chore

#85 feat: 일반 회원 배송 목록 조회
  src/components/sidebar/MemberSidebar.vue
  src/router/memberRouter.js
  src/views/member/myPage/MemberDeliveryList.vue
Labels: 🥦 feature

#91 feat: 메인페이지 라이브 제외 구현
  src/router/index.js
  src/views/main/MainPage.vue
  src/views/product/farm/FarmList.vue
Labels: 🥦 feature

#92 feat: 리뷰 생성, 수정, 삭제, 리스트, 디테일 구현
  src/router/index.js
  src/router/reviewRouter.js
  src/views/product/review/FarmReviewList.vue
  src/views/product/review/ReviewCreate.vue
  src/views/product/review/ReviewDetail.vue
  src/views/product/review/ReviewUpdate.vue
Labels: 🥦 feature

#93 feat: 채팅 연동 및 추가 화면 구현
  package.json
  src/views/live/chat/ChatBox.vue
  src/views/live/live/LiveList.vue
  src/views/live/live/LiveSession.vue
Labels: 🥦 feature

#99 chore: 상품 등록 및 수정 화면 수정
  src/views/product/package/ProductCreate.vue
  src/views/product/seller/ProductUpdate.vue
Labels: 🧹 chore

#102 chore: 농장 패키지 정보 화면 수정
  src/views/live/chat/ChatBox.vue
  src/views/live/live/LiveList.vue
  src/views/product/farm/FarmPackageList.vue
Labels: 🧹 chore

#107 feat: farm 및 package elastic search 검색 구현
  src/components/header/MainHeader.vue
Labels: 🥦 feature

#104 feat: 농장 정보 수정
  src/components/sidebar/SellerSidebar.vue
  src/router/farmRouter.js
  src/views/product/farm/FarmInfoUpdate.vue
Labels: 🥦 feature

#106 feat: seller 비밀번호 변경
  src/components/sidebar/SellerSidebar.vue
  src/router/sellerRouter.js
  src/views/product/seller/SellerPasswordUpdate.vue
Labels: 🥦 feature

#108 style: 메인페이지와 farm 수정
  src/views/main/MainPage.vue
  src/views/product/farm/FarmList.vue
Labels: 🎨style

#110 style: 메인 페이지, farm 페이지 수정
  src/views/main/MainPage.vue
  src/views/product/farm/FarmList.vue
Labels: 🎨style

#113 feat: es 전체 통합 검색 구현
  src/components/header/MainHeader.vue
Labels: 🥦 feature

#122 chore: 자잘한 디자인 수정
  src/views/order/coupon/CouponList.vue
  src/views/product/review/ReviewCreate.vue
  src/views/product/review/ReviewDetail.vue
  src/views/product/seller/FarmNoticeSellerDetail.vue
  src/views/product/seller/SellerReviewDetail.vue
  src/views/product/seller/SellerReviewList.vue
Labels: 🧹 chore

#125 chore: 썸네일 이미지에 커서 올렸을 때 영상 출력 및 favorites 목록 출력 디자인 수정
  src/views/live/live/LiveList.vue
Labels: 🧹 chore

#127 chore: websocket 연결 해제 및 강퇴 기능 구현
  src/views/live/chat/ChatBox.vue
  src/views/live/live/LiveSession.vue
Labels: 🥦 feature, 🧹 chore

#123 feat: 판매 중인 전체 패키지 리스트 조회
  src/components/header/MainHeader.vue
  src/router/index.js
  src/router/productRouter.js
  src/views/product/package/AllProductList.vue
Labels: 🥦 feature

#128 fix: 메인페이지, 농장 리스트 페이지 디자인 수정, 좋아요 API 연동
  src/App.vue
  src/components/footer/MainFooter.vue
  src/components/header/MainHeader.vue
  src/views/main/MainPage.vue
  src/views/product/farm/FarmList.vue
Labels: 🥦 feature, 🧹 chore

#130 chore: seller 리뷰페이지 & 농장 detail 디자인 수정
  src/components/menubar/FarmMenuComponent.vue
  src/views/product/farm/FarmDetailDescription.vue
  src/views/product/farm/FarmPackageList.vue
  src/views/product/farmNotice/FarmNoticeList.vue
  src/views/product/farmNotice/NoticeDetailWithComment.vue
  src/views/product/review/FarmReviewList.vue
  src/views/product/seller/SellerReviewDetail.vue
  src/views/product/seller/SellerReviewList.vue
Labels: 🎨style

#134 feat: 상품 디테일 화면 구현
  src/router/farmRouter.js
  src/views/product/farm/FarmPackageDetail.vue
  src/views/product/farm/FarmPackageList.vue
  src/views/product/review/FarmReviewList.vue
  src/views/product/review/ReviewDetail.vue
  src/views/product/seller/FarmNoticeSellerDetail.vue
Labels: 🥦 feature, 🧹 chore

#136 feat: 판매자 강퇴 기능 추가
  src/views/live/chat/ChatBox.vue
  src/views/live/live/LiveSession.vue
Labels: 🥦 feature, 🧹 chore

#137 chore: 라이브 & 채팅 디자인 수정
  src/components/video/UserVideo.vue
  src/views/live/chat/ChatBox.vue
  src/views/live/live/LiveList.vue
  src/views/live/live/LiveSession.vue
  src/views/main/MainPage.vue
Labels: 🧹 chore, 🎨style

#141 chore&feat: 라이브 관련 추가 및 수정 요청사항 적용 + 디자인 수정
  src/App.vue
  src/components/header/MainHeader.vue
  src/components/sidebar/SellerSidebar.vue
  src/views/live/chat/ChatBox.vue
  src/views/live/live/LiveList.vue
  src/views/live/live/LiveSession.vue
  src/views/main/MainPage.vue
Labels: 🥦 feature, 🧹 chore, 🎨style

#140 feat: 결제 페이지 기능 일부 연결
  package.json
  src/router/index.js
  src/router/memberRouter.js
  src/router/orderRouter.js
  src/views/live/live/LiveList.vue
  src/views/main/MainPage.vue
  src/views/member/myPage/MemberMyPage.vue
  src/views/order/coupon/MemberCouponList.vue
  src/views/order/payment/PaymentView.vue
  src/views/product/farm/FarmList.vue
Labels: 🥦 feature

#144 feat: seller도 공지사항 > 댓글에 작성/수정/조회/삭제 가능
  src/App.vue
  src/components/menubar/FarmMenuComponent.vue
  src/views/product/farmNotice/NoticeDetailWithComment.vue
Labels: 🥦 feature, 🧹 chore, 🎨style

#146 fix: 담당 파트 디자인 및 디테일 수정
  src/views/product/farm/FarmInfoUpdate.vue
  src/views/product/seller/SellerPasswordUpdate.vue
Labels: 🚧 fix

#147 fix: 회원 배송 조회 다대일 수정
  src/views/member/myPage/MemberDeliveryList.vue
Labels: 🚧 fix

#150 fix: 마이페이지 배송 목록 정렬
  src/views/member/myPage/MemberDeliveryList.vue
Labels: 🚧 fix

#151 feat&chore: 목록이 출력되고 라이브 프리뷰 자동 재생되도록 구현
  src/views/live/live/LiveList.vue
  src/views/live/live/LiveSession.vue
Labels: 🥦 feature, 🧹 chore

#148 feat: 결제 화면, 결제 결과 화면 완성
  package.json
  src/router/farmRouter.js
  src/router/orderRouter.js
  src/router/productRouter.js
  src/views/order/payment/PaymentResultView.vue
  src/views/order/payment/PaymentView.vue
  src/views/product/farm/FarmList.vue
  src/views/product/farm/FarmPackageDetail.vue
Labels: 🥦 feature

#159 style: 메인페이지 디자인 수정
  src/components/slide/BestFarmSlide.vue
  src/components/slide/BestPackageSlide.vue
  src/views/main/MainPage.vue
Labels: 🎨style, 🔨refactor

#160 chore: 판매자 회원가입 화면 수정
  src/views/member/login/MemberSignIn.vue
  src/views/product/seller/SellerSignUp.vue
Labels: 🧹 chore

#162 fix: 판매 패키지 목록 디자인 수정
  src/views/product/package/AllProductList.vue
Labels: 🚧 fix, 🎨style

#163 chore: 마이페이지> 내 정보 수정 & 정기구독 페이지 디자인 수정
  src/components/sidebar/MemberSidebar.vue
  src/router/memberRouter.js
  src/views/member/myPage/MemberAddressUpdate.vue
  src/views/member/myPage/MemberPhoneUpdate.vue
  src/views/member/myPage/MemberSubscribeManage.vue
  src/views/product/farm/FarmPackageDetail.vue
Labels: 🧹 chore, 🎨style

#164 fix: 라이브 화면 수정
  src/views/live/chat/ChatBox.vue
  src/views/live/live/LiveSession.vue
Labels: 🥦 feature, 🚧 fix

#170 chore: 마이페이지 > 내 정보 조회 & 쿠폰 조회 디자인 수정
  src/views/live/live/LiveSession.vue
  src/views/member/myPage/MemberMyPage.vue
  src/views/order/coupon/CouponList.vue
  src/views/order/coupon/MemberCouponList.vue
  src/views/product/seller/ProductList.vue
Labels: 🧹 chore, 🎨style

#174 fix: 농장 배너 이미지 등록 화면 수정
  package.json
  src/components/menubar/FarmMenuComponent.vue
  src/views/product/farm/FarmCreate.vue
Labels: 🧹 chore, 🚧 fix

#171 fix: 판매자 페이지 > 판매건수, 매출 내역 페이지 수정
  package.json
  src/components/slide/BestPackageSlide.vue
  src/views/product/seller/SellerSalesDetail.vue
Labels: 🚧 fix

#168 fix: 농장 정보 수정화면 변경
  src/views/product/farm/FarmInfoUpdate.vue
Labels: 🚧 fix, 🎨style

#176 fix: 모달 디자인 변경
  src/assets/inongLogo.png
  src/components/header/MainHeader.vue
  src/views/member/login/GoogleCallback.vue
  src/views/member/login/MemberSignIn.vue
  src/views/member/login/MemberSignUp.vue
  src/views/member/myPage/MemberMyPage.vue
  src/views/order/receipt/MemberPaymentReceipt.vue
Labels: 🚧 fix, 🎨style

#179 fix: 농장 생성 화면 수정
  src/components/header/MainHeader.vue
  src/components/menubar/FarmMenuComponent.vue
  src/views/product/farm/FarmCreate.vue
Labels: 🧹 chore, 🚧 fix

#182 feat: 정기 결제 수단 등록 API 연동
  src/components/header/MainHeader.vue
  src/views/member/myPage/MemberSubscribeManage.vue
  src/views/order/payment/PaymentView.vue
Labels: 🥦 feature

#183 feat: 패키지 위시리스트 구현
  src/views/product/package/AllProductList.vue
Labels: 🥦 feature

#184 chore: 농장 수정 시 배너 이미지 수정 화면 변경
  src/views/product/farm/FarmCreate.vue
  src/views/product/farm/FarmInfoUpdate.vue
Labels: 🧹 chore

#189 fix: 결제 수단 등록 에러 수정
  src/components/footer/MainFooter.vue
  src/views/member/login/GoogleCallback.vue
  src/views/member/myPage/MemberSubscribeManage.vue
  src/views/order/payment/PaymentView.vue
  src/views/product/farm/FarmList.vue
  src/views/product/seller/SellerSalesDetail.vue
Labels: 🚧 fix

#193 chore: 스크랩농장 / 위시리스트 수정
  src/components/sidebar/MemberSidebar.vue
  src/views/member/myPage/MemberFavorite.vue
Labels: 🧹 chore, 🎨style

#194 chore: 라이브 화면 안에서 시청 인원 표시
  src/views/live/chat/ChatBox.vue
Labels: 🧹 chore

#199 Enhancement : elastic search 디벨롭
  src/components/header/MainHeader.vue
Labels: enhancement

#200 fix: 결제 페이지 관련 오류 수정
  src/components/header/MainHeader.vue
  src/views/main/MainPage.vue
  src/views/order/payment/PaymentView.vue
  src/views/product/farm/FarmList.vue
  src/views/product/package/AllProductList.vue
Labels: 🚧 fix

#203 fix: 패키지 BEST 10 슬라이드 변경
  src/components/slide/Best10PackageSlide.vue
  src/views/product/package/AllProductList.vue
Labels: 🚧 fix, 🎨style

#207 feat: 메인 페이지 > live best5 출력
  src/components/menubar/FarmMenuComponent.vue
  src/views/live/live/LiveList.vue
  src/views/live/live/LiveListBest.vue
  src/views/main/MainPage.vue
  src/views/product/farm/FarmList.vue
Labels: 🥦 feature, 🧹 chore, 🎨style

#210 fix: 완료 모달, 기능 모달 등 전체적인 디자인 수정
  src/views/live/live/LiveList.vue
  src/views/main/MainPage.vue
  src/views/member/myPage/MemberPhoneUpdate.vue
  src/views/order/coupon/CouponCreate.vue
  src/views/product/farm/FarmCreate.vue
  src/views/product/farm/FarmInfoUpdate.vue
  src/views/product/farmNotice/FarmNoticeCreate.vue
  src/views/product/farmNotice/FarmNoticeUpdate.vue
  src/views/product/farmNotice/NoticeDetailWithComment.vue
  src/views/product/package/ProductCreate.vue
  src/views/product/review/ReviewCreate.vue
  src/views/product/review/ReviewDetail.vue
  src/views/product/seller/FarmNoticeSellerDetail.vue
  src/views/product/seller/ProductList.vue
  src/views/product/seller/ProductUpdate.vue
  src/views/product/seller/SellerReviewDetail.vue
Labels: 🚧 fix, 🎨style

#212 fix: 모달관련 문제, reload 관련 문제 등 수정
  src/views/order/coupon/CouponCreate.vue
  src/views/product/farm/FarmPackageDetail.vue
  src/views/product/review/FarmReviewList.vue
  src/views/product/review/ReviewUpdate.vue
  src/views/product/seller/FarmNoticeSellerDetail.vue
Labels: 🚧 fix, 🎨style

#215 feat: 구독 취소 기능 및 화면 구현
  src/views/member/myPage/MemberSubscribeManage.vue
Labels: 🥦 feature

#216 fix: 알림 페이지 기능만 구현, 로그아웃해도 알림이 남아있는 오류 수정
  src/components/header/MainHeader.vue
  src/router/index.js
  src/router/notificationRouter.js
  src/views/member/notification/NotificationView.vue
Labels: 🥦 feature, 🚧 fix

#219 feat: 알림 카드를 누르면 적절한 화면으로 라우팅
  src/components/header/MainHeader.vue
Labels: enhancement

#221 fix: 상품 및 농장 검색 기능 보완
  src/views/product/farm/FarmList.vue
  src/views/product/package/AllProductList.vue
Labels: enhancement, 🚧 fix, 🎨style

#225 fix: 로그아웃시 fcmToken 삭제 로직 추가
  src/components/header/MainHeader.vue
Labels: 🚧 fix

#234 feat: 쿠폰 등록 및 발급 화면 구현
  src/views/live/chat/ChatBox.vue
  src/views/live/live/LiveSession.vue
Labels: 🥦 feature, 🧹 chore

#235 fix: 메인 페이지 보완
  public/eating.png
  public/farm-pic.jpg
  public/farmer.png
  public/grain.jpg
  public/order.png
  public/vegan.png
  public/vege.png
  src/views/main/MainPage.vue
Labels: 🚧 fix

#238 fix: 농장 목록 페이지 아이콘 수정
  public/egg.png
  public/fruit.png
  public/meat.png
  public/milk.png
  public/rice.png
  public/vegetable.png
  src/views/product/farm/farmListSample.vue
Labels: 🚧 fix, 🎨style

#240 feat: package list & package detail에 세일 구현
  src/components/menubar/FarmMenuComponent.vue
  src/components/slide/Best10PackageSlide.vue
  src/views/main/MainPage.vue
  src/views/product/farm/FarmPackageDetail.vue
  src/views/product/package/AllProductList.vue
Labels: 🥦 feature, 🎨style

#239 feat: 알림 단건 읽음 처리 구현
  src/components/header/MainHeader.vue
Labels: 🥦 feature

#243 chore: 농장 패키지 목록 수정
  src/views/product/farm/FarmPackageList.vue
  src/views/product/farm/farmListSample.vue
Labels: 🧹 chore

#244 fix: 메인페이지 스크롤 수정
  src/components/slide/BestFarmSlide.vue
Labels: 🚧 fix, 🎨style

#246 feat: 사장님 페이지 > 할인 목록 구현
  src/components/sidebar/SellerSidebar.vue
  src/components/slide/Best10PackageSlide.vue
  src/router/sellerRouter.js
  src/views/product/farm/FarmPackageDetail.vue
  src/views/product/package/AllProductList.vue
  src/views/product/seller/SellerDiscountManagement.vue
Labels: 🥦 feature

#248 feat: 비로그인 라이브 접속 차단
  src/views/live/chat/ChatBox.vue
  src/views/live/live/LiveList.vue
Labels: 🥦 feature, 🧹 chore

#250 fix: 주문 번호 추가, 결제 페이지에서 각종 에러 수정
  src/views/order/payment/PaymentResultView.vue
  src/views/order/payment/PaymentView.vue
  src/views/product/seller/SellerSalesDetail.vue
Labels: 🚧 fix

#253 fix&style: 농장 프로필 디자인 수정 및 농장과 메인 패키지 상품에 할인 추가
  src/components/menubar/FarmMenuComponent.vue
  src/components/slide/BestPackageSlide.vue
  src/views/product/farm/FarmPackageList.vue
  src/views/product/farm/farmListSample.vue
  src/views/product/package/AllProductList.vue
  src/views/product/seller/SellerDiscountManagement.vue
Labels: 🚧 fix, 🎨style

#252 feat: 채팅 이모지 기능 구현
  src/views/live/chat/ChatBox.vue
Labels: 🥦 feature

#254 Chore/249
  package.json
  src/views/order/coupon/CouponCreate.vue
  src/views/product/farmNotice/FarmNoticeUpdate.vue
  src/views/product/review/ReviewUpdate.vue
  src/views/product/seller/SellerDiscountCreate.vue
  src/views/product/seller/SellerDiscountManagement.vue
Labels: 🥦 feature, 🧹 chore

#256 feat: 할인 수정, 삭제 구현
  src/views/product/farm/FarmPackageList.vue
  src/views/product/seller/SellerDiscountCreate.vue
  src/views/product/seller/SellerDiscountManagement.vue
  src/views/product/seller/SellerDiscountUpdate.vue
Labels: 🥦 feature, 🧹 chore

#258 chore: 자잘한 디자인 및 오류 수정
  public/coupon1.png
  public/coupon3.png
  src/components/slide/Best10PackageSlide.vue
  src/views/order/coupon/MemberCouponList.vue
  src/views/order/payment/PaymentView.vue
  src/views/product/farm/FarmPackageDetail.vue
  src/views/product/review/ReviewUpdate.vue
  src/views/product/seller/SellerReviewList.vue
Labels: 🧹 chore

#261 feat: product detail 추가
  package.json
  src/assets/youtube.png
  src/views/product/farm/FarmPackageDetail.vue
Labels: 🥦 feature
